const el = (id) => document.getElementById(id);

export function getDomElements() {
  return {
    panelEl: el("panel"),
    panelScrimEl: el("panelScrim"),
    mapWrapEl: el("mapWrap"),
    mapFallbackEl: el("mapFallback"),
    mobileToggleEl: el("mobileToggle"),
    mobileToggleFloatingEl: el("mobileToggleFloating"),
    searchEl: el("searchInput"),
    typeEl: el("typeFilter"),
    statusEl: el("statusFilter"),
    countryEl: el("countryFilter"),
    subjectEl: el("subjectFilter"),
    presetsEl: el("quickPresets"),
    sortEl: el("sortOrder"),
    nearestBtnEl: el("nearestBtn"),
    favoritesOnlyEl: el("favoritesOnly"),
    fitResultsEl: el("fitResults"),
    viewportOnlyEl: el("viewportOnly"),
    resetFiltersEl: el("resetFilters"),
    exportCsvEl: el("exportCsv"),
    exportGeoJsonEl: el("exportGeoJson"),
    shareLinkEl: el("shareLink"),
    shareSheetEl: el("shareSheet"),
    passportEl: el("checkpointPassport"),
    datasetChangesEl: el("datasetChanges"),
    recentEl: el("recent"),
    nearestOpenEl: el("nearestOpen"),
    compareEl: el("compare"),
    legendEl: el("legend"),
    statsEl: el("stats"),
    listEl: el("list"),
    emptyEl: el("emptyState"),
    loaderEl: el("loader"),
    loaderProgressEl: el("loaderProgress"),
    loaderTextEl: el("loaderText"),
    offlineStatusEl: el("offlineStatus"),
    styleToggleEl: el("styleToggle"),
    boundariesToggleEl: el("boundariesToggle"),
    roadsToggleEl: el("roadsToggle"),
    themeToggleEl: el("themeToggle"),
    geoBtnEl: el("geoBtn")
  };
}
